### ISSUE TITLE
Add JSON Formatter to collect logs for different systems e.g. logstash

### ISSUE THREAD

**Issue by spetz83** [zendframework/zend-log#13]
This was an issue originally opened on the ZF2 repository. 

Link to original: https://github.com/zendframework/zf2/issues/7466

Original post from user sandrokeil: 

"I want to send logs from my PHP Docker container to stderr and analyze it with the ELK (elasticsearch, logstash, kibana) stack.

Currently there are different formatters e.g. XML, but a JSON formatter is missing. If we have a JSON Log formatter in ZF2, it gives us the possibility to write standardized plugins for different systems (logstash, fluentd).

Any thoughts or pitfalls for this?"

**Comment by samsonasik** [comment]
can be closed in favor of https://github.com/zendframework/zend-log/pull/58
