### ISSUE TITLE
Document all writers

### ISSUE THREAD

**Issue by weierophinney** [zendframework/zend-log#25]
The following log writers are currently undocumented:
- `Zend\Log\Writer\Mail`
- `Zend\Log\Writer\MongoDB`
- `Zend\Log\Writer\Syslog`
- `Zend\Log\Writer\ZendMonitor`

Documentation should include:
- constructor arguments
- constructor option names
- any information specific to their implementations

**Comment by curtiskelsey** [comment]
I'm a Long time Zend Framework user but never made any contributions (shame on me). Looks like a good place to start. I'll see what I can whip up for this.
