### ISSUE TITLE
PSR-3 compliants?

### ISSUE THREAD

**Issue by dlevel** [zendframework/zend-log#35]
Why does the interface Zend\Log\LoggerInterface does not respect the PSR-3 one?

**Comment by Ocramius** [comment]
Mostly because it was designed much (MUCH!) earlier than PSR-3

**Comment by Ocramius** [comment]
PSR-3 compliance is already provided, as [documented](https://github.com/zendframework/zend-log/blob/015219b23d9d118992944ab3ad268d444592ab19/doc/book/psr3.md)

**Comment by dlevel** [comment]
Hi, 
I've already learned this part of the doc before asking you this question.
My question was because the class Zend\Log\Logger does not respect the PSR3 interface.

I'm not able to use the adapter specified in the documentation because I already need to use the Syslog one for my purpose.

I do agree that this module was develop before PSR-3 and that's why I wanted to know if a PR could be accepted for that?

**Comment by Ocramius** [comment]
Changing interfaces is a major backwards-incompatible change, so we wouldn't be able to change the logger interface anyway (the PR would be rejected)

**Comment by dlevel** [comment]
Ok I understand that point.

**Comment by halfpastfouram** [comment]
@Ocramius Couldn't that be resolved by having the `Zend\Log\LoggerInterface` extend `Psr\Log\LoggerInterface` or am I missing something?

**Comment by Ocramius** [comment]
Keep the interfaces and implementations separated: mixing interfaces is just trouble, as you risk starting to couple to both without noticing, and you may have signature collisions.

**Comment by halfpastfouram** [comment]
I totally agree, but a lot of middleware doesn't respect that thought. Thanks for your reply anyways.
