### ISSUE TITLE
[ZF3] Log & Session: MongoDB to MongoDb (CamelCase)

### ISSUE THREAD

**Issue by GeeH** [zendframework/zend-log#52]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7041
User: @marc-mabe
Created On: 2014-12-15T20:58:33Z
Updated At: 2014-12-16T12:48:40Z
Body
see #7034

---
### Comment

User: @Ocramius
Created On: 2014-12-16T05:09:49Z
Updated At: 2014-12-16T05:09:49Z
Body
While I agree with the change, I think it's kind-of an useless change for the 3.x milestone (of the type that makes people mad on upgrade: raging mad). I'll keep the PR open anyway.

---
### Comment

User: @marc-mabe
Created On: 2014-12-16T07:43:12Z
Updated At: 2014-12-16T07:43:12Z
Body
@Ocramius Because it's not a big deal to keep this I'm ok with it. But in my opinion the BC break is minimal because most uses some kind of classmap autoloder in production and only filesystem bases autoloaders on case sensitive filesystems are effected. Additionally this kind of break is simple to find and to fix.

---
### Comment

User: @Ocramius
Created On: 2014-12-16T07:59:51Z
Updated At: 2014-12-16T07:59:51Z
Body

> production and only filesystem bases autoloaders on case sensitive filesystems are effected

Reads "production systems not run by crazy people" :-)

---

**Comment by weierophinney** [comment]
> only filesystem bases autoloaders on case sensitive filesystems

You realize that's most Linux filesystems, which are the typical deployment target, right?

As such, I'm closing; I agree with @Ocramius that this is the kind of change that will cause unwarranted problems on upgrade.
