### ISSUE TITLE
[php 7.2] incompatible prototype

### ISSUE THREAD

**Issue by remicollet** [zendframework/zend-log#76]
`PHP Fatal error:  Declaration of Zend\Log\Writer\FingersCrossed::setFormatter($formatter) must be compatible with Zend\Log\Writer\AbstractWriter::setFormatter($formatter, ?array $options = NULL) in ...`

**Comment by naprstek** [comment]
Sorry, Fix #76 is not enough. In this case is broken interface implementation. Interface WriterInterface declares setFormatter($formatter), but AbstractWritter implements it as setFormatter($formatter, array $options = null) and other classes inherits wrong implementation from AbstractWriter.

There must be done corrects for whole chain. Must be either replaced AbstractWritter::setFormatter or changed WriterInterface::setFormatter and all inheritted classes.

By Vladimir
